-- MySQL Script generated by MySQL Workbench
-- Fri May  7 09:26:07 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema boutique
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema boutique
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `boutique` DEFAULT CHARACTER SET utf8 ;
USE `boutique` ;

-- -----------------------------------------------------
-- Table `boutique`.`membre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boutique`.`membre` (
  `id_membre` INT NOT NULL AUTO_INCREMENT,
  `pseudo` VARCHAR(20) NULL,
  `nom` VARCHAR(20) NULL,
  `prenom` VARCHAR(20) NULL,
  `email` VARCHAR(50) NULL,
  `civilite` ENUM('m', 'f') NULL,
  `ville` VARCHAR(20) NULL,
  `code_postal` INT(5) NULL,
  `adresse` VARCHAR(45) NULL,
  `statut` INT(1) NULL,
  PRIMARY KEY (`id_membre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `boutique`.`etat_commande`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boutique`.`etat_commande` (
  `id_etat` INT NOT NULL AUTO_INCREMENT,
  `etat` VARCHAR(45) NULL,
  PRIMARY KEY (`id_etat`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `boutique`.`commande`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boutique`.`commande` (
  `id_commandes` INT NOT NULL AUTO_INCREMENT,
  `commandescol` VARCHAR(45) NULL,
  `membre_id_membre` INT NOT NULL,
  `etat_commande_id_etat` INT NOT NULL,
  PRIMARY KEY (`id_commandes`, `membre_id_membre`, `etat_commande_id_etat`),
  INDEX `fk_commandes_membre1_idx` (`membre_id_membre` ASC) VISIBLE,
  INDEX `fk_commandes_etat_commande1_idx` (`etat_commande_id_etat` ASC) VISIBLE,
  CONSTRAINT `fk_commandes_membre1`
    FOREIGN KEY (`membre_id_membre`)
    REFERENCES `boutique`.`membre` (`id_membre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_commandes_etat_commande1`
    FOREIGN KEY (`etat_commande_id_etat`)
    REFERENCES `boutique`.`etat_commande` (`id_etat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `boutique`.`categorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boutique`.`categorie` (
  `id_categorie` INT NOT NULL AUTO_INCREMENT,
  `categorie` VARCHAR(255) CHARACTER SET 'utf8' NULL,
  PRIMARY KEY (`id_categorie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `boutique`.`sous_categorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boutique`.`sous_categorie` (
  `id_sous_categorie` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(255) NULL,
  PRIMARY KEY (`id_sous_categorie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `boutique`.`produit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boutique`.`produit` (
  `id_produit` INT NOT NULL AUTO_INCREMENT,
  `titre` VARCHAR(100) NULL,
  `description` TEXT NULL,
  `photo` VARCHAR(250) NULL,
  `prix` FLOAT NULL,
  `categorie_id_categorie` INT NOT NULL,
  `sous_categorie_id_sous_categorie` INT NOT NULL,
  `sous_categorie_categorie_id_categorie` INT NOT NULL,
  `taille_id_taille` INT(11) NOT NULL,
  PRIMARY KEY (`id_produit`, `categorie_id_categorie`, `sous_categorie_id_sous_categorie`, `sous_categorie_categorie_id_categorie`, `taille_id_taille`),
  INDEX `fk_produit_categorie1_idx` (`categorie_id_categorie` ASC) VISIBLE,
  INDEX `fk_produit_sous_categorie1_idx` (`sous_categorie_id_sous_categorie` ASC, `sous_categorie_categorie_id_categorie` ASC) VISIBLE,
  CONSTRAINT `fk_produit_categorie1`
    FOREIGN KEY (`categorie_id_categorie`)
    REFERENCES `boutique`.`categorie` (`id_categorie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produit_sous_categorie1`
    FOREIGN KEY (`sous_categorie_id_sous_categorie`)
    REFERENCES `boutique`.`sous_categorie` (`id_sous_categorie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `boutique`.`details_commande`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boutique`.`details_commande` (
  `id_details_commandes` INT NOT NULL AUTO_INCREMENT,
  `commandes_id_commandes` INT NOT NULL,
  `produit_id_produit` INT NOT NULL,
  `nom` TEXT NULL,
  `prenom` TEXT NULL,
  `adresse` TEXT NULL,
  `telephone` INT(15) NULL,
  `code_postal` INT(5) NULL,
  `quantite` INT(3) NULL,
  `prix` INT(3) NULL,
  PRIMARY KEY (`id_details_commandes`, `commandes_id_commandes`, `produit_id_produit`),
  INDEX `fk_details_commandes_commandes_idx` (`commandes_id_commandes` ASC) VISIBLE,
  INDEX `fk_details_commandes_produit1_idx` (`produit_id_produit` ASC) VISIBLE,
  CONSTRAINT `fk_details_commandes_commandes`
    FOREIGN KEY (`commandes_id_commandes`)
    REFERENCES `boutique`.`commande` (`id_commandes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_details_commandes_produit1`
    FOREIGN KEY (`produit_id_produit`)
    REFERENCES `boutique`.`produit` (`id_produit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
